var FurList =[
	[29,19,17,1200,59.95,'https://www.fourrureshop.fr/produit/tissu-fausse-fourrure-facon-vison-brun-naturel-3125/'],
	[151,209,201,1200,16.99,'https://bigzfabric.com/collections/candy-shag-faux-fur-fabric/products/candy-shag-faux-fur-fabric-aqua-sold-by-the-yard-second-quality-goods'], // en $/m pour lui et les suivants
	[133,116,168,1200,23.50,'https://bigzfabric.com/collections/candy-shag-faux-fur-fabric/products/candy-shag-faux-fur-fabric-purple-sold-by-the-yard-ecoshagtm'],
	[207,185,211,1200,23.50,'https://bigzfabric.com/collections/candy-shag-faux-fur-fabric/products/candy-shag-faux-fur-fabric-lavender-sold-by-the-yard-ecoshagtm'],
	[154,146,135,1200,23.50,'https://bigzfabric.com/collections/candy-shag-faux-fur-fabric/products/candy-shag-faux-fur-fabric-gray-sold-by-the-yard-ecoshagtm'],
	[79,70,71,1200,23.50,'https://bigzfabric.com/collections/candy-shag-faux-fur-fabric/products/candy-shag-faux-fur-fabric-black-sold-by-the-yard-ecoshagtm'],
	[209,146,58,1200,23.50,'https://bigzfabric.com/collections/candy-shag-faux-fur-fabric/products/candy-shag-faux-fur-fabric-amber-sold-by-the-yard-ecoshagtm'],
	[242,180,194,1200,23.50,'https://bigzfabric.com/collections/candy-shag-faux-fur-fabric/products/candy-shag-faux-fur-fabric-bubble-gum-sold-by-the-yard-ecoshagtm'],
	[82,116,75,9999,25.50,'https://bigzfabric.com/collections/faux-fake-fur-arctic-alaskan-husky-long-pile-fabric/products/lime-arctic-alaskan-husky-long-pile-fabric-sold-by-the-yard-ecoshagreg'],
	[117,45,12,9999,25.50,'https://bigzfabric.com/collections/faux-fake-fur-arctic-alaskan-husky-long-pile-fabric/products/tangerine-arctic-alaskan-husky-long-pile-fabric-sold-by-the-yard-ecoshagreg'],
	[142,117,47,9999,25.50,'https://bigzfabric.com/collections/faux-fake-fur-arctic-alaskan-husky-long-pile-fabric/products/yellow-arctic-alaskan-husky-long-pile-fabric-sold-by-the-yard-ecoshagreg'],
	[123,116,97,9999,25.50,'https://bigzfabric.com/collections/faux-fake-fur-arctic-alaskan-husky-long-pile-fabric/products/faux-fake-fur-arctic-alaskan-husky-long-pile-fabric-ivory-sold-by-the-yard-ecoshag-sup-tm-sup'],
	[177,151,126,9999,25.50,'https://bigzfabric.com/collections/faux-fake-fur-arctic-alaskan-husky-long-pile-fabric/products/faux-fake-fur-arctic-alaskan-husky-long-pile-fabric-blonde-sold-by-the-yard-ecoshag-sup-tm-sup'],
	[95,186,183,9999,25.50,'https://bigzfabric.com/collections/faux-fake-fur-arctic-alaskan-husky-long-pile-fabric/products/faux-fake-fur-arctic-alaskan-husky-long-pile-fabric-turquoise-sold-by-the-yard-ecoshag-sup-tm-sup'],
	[76,202,141,9999,25.50,'https://bigzfabric.com/collections/faux-fake-fur-arctic-alaskan-husky-long-pile-fabric/products/faux-fake-fur-arctic-alaskan-husky-long-pile-fabric-mint-sold-by-the-yard-ecoshagtm'],
	[61,29,19,9999,25.50,'https://bigzfabric.com/collections/faux-fake-fur-arctic-alaskan-husky-long-pile-fabric/products/faux-fake-fur-arctic-alaskan-husky-long-pile-fabric-burgundy-sold-by-the-yard-ecoshagtm'],
	[113,112,128,9999,25.50,'https://bigzfabric.com/collections/faux-fake-fur-arctic-alaskan-husky-long-pile-fabric/products/faux-fake-fur-arctic-alaskan-husky-long-pile-fabric-ice-blue-sold-by-the-yard-ecoshagtm'],
	[172,77,30,9999,25.50,'https://bigzfabric.com/collections/faux-fake-fur-arctic-alaskan-husky-long-pile-fabric/products/faux-fake-fur-arctic-alaskan-husky-long-pile-fabric-amber-sold-by-the-yard-ecoshagtm'],
	[126,126,126,9999,25.50,'https://bigzfabric.com/collections/faux-fake-fur-arctic-alaskan-husky-long-pile-fabric/products/faux-fake-fur-arctic-alaskan-husky-long-pile-fabric-gray-sold-by-the-yard'],
	[196,71,109,9999,25.50,'https://bigzfabric.com/collections/faux-fake-fur-arctic-alaskan-husky-long-pile-fabric/products/faux-fake-fur-arctic-alaskan-husky-long-pile-fabric-pink-sold-by-the-yard'],
	[164,36,81,9999,25.50,'https://bigzfabric.com/collections/faux-fake-fur-arctic-alaskan-husky-long-pile-fabric/products/faux-fake-fur-arctic-alaskan-husky-long-pile-fabric-fuchsia-sold-by-the-yard'],
	[176,31,23,9999,25.50,'https://bigzfabric.com/collections/faux-fake-fur-arctic-alaskan-husky-long-pile-fabric/products/faux-fake-fur-arctic-alaskan-husky-long-pile-fabric-red-sold-by-the-yard'],
	[54,62,82,9999,25.50,'https://bigzfabric.com/collections/faux-fake-fur-arctic-alaskan-husky-long-pile-fabric/products/faux-fake-fur-arctic-alaskan-husky-long-pile-fabric-blue-sold-by-the-yard'],
	[67,34,96,9999,25.50,'https://bigzfabric.com/collections/faux-fake-fur-arctic-alaskan-husky-long-pile-fabric/products/faux-fake-fur-arctic-alaskan-husky-long-pile-fabric-purple-sold-by-the-yard'],
	[97,77,45,9999,19.99,'https://bigzfabric.com/collections/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-4-pile-length/products/light-brown-solid-gorilla-animal-long-pile-fabric-sold-by-the-yard-1'],
	[69,74,72,9999,19.99,'https://bigzfabric.com/collections/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-4-pile-length/products/charcoal-solid-gorilla-animal-long-pile-fabric-sold-by-the-yard-1'],
	[195,176,125,9999,19.99,'https://bigzfabric.com/collections/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-4-pile-length/products/blone-solid-gorilla-animal-long-pile-fabric-sold-by-the-yard'],
	[208,198,190,9999,19.99,'https://bigzfabric.com/collections/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-4-pile-length/products/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-platinum-sold-by-the-yard-ecoshag'],
	[249,240,214,9999,19.99,'https://bigzfabric.com/collections/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-4-pile-length/products/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-ivory-sold-by-the-yard-ecoshag'],
	[150,74,22,9999,19.99,'https://bigzfabric.com/collections/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-4-pile-length/products/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-amber-sold-by-the-yard-ecoshagtm'],
	[57,53,52,9999,19.99,'https://bigzfabric.com/collections/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-4-pile-length/products/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-pewter-sold-by-the-yard'],
	[26,22,13,9999,19.99,'https://bigzfabric.com/collections/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-4-pile-length/products/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-brown-sold-by-the-yard'],
	[233,197,41,9999,19.99,'https://bigzfabric.com/collections/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-4-pile-length/products/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-yellow-sold-by-the-yard'],
	[91,224,219,9999,19.99,'https://bigzfabric.com/collections/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-4-pile-length/products/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-turquoise-sold-by-the-yard'],
	[238,48,28,9999,19.99,'https://bigzfabric.com/collections/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-4-pile-length/products/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-red-sold-by-the-yard'],
	[238,86,3,9999,19.99,'https://bigzfabric.com/collections/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-4-pile-length/products/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-orange-sold-by-the-yard'],
	[79,193,36,9999,19.99,'https://bigzfabric.com/collections/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-4-pile-length/products/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-lime-sold-by-the-yard'],
	[202,198,189,9999,19.99,'https://bigzfabric.com/collections/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-4-pile-length/products/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-grey-frost-sold-by-the-yard'],
	[218,186,139,9999,19.99,'https://bigzfabric.com/collections/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-4-pile-length/products/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-camel-sold-by-the-yard'],
	[220,219,215,9999,19.99,'https://bigzfabric.com/collections/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-4-pile-length/products/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-white-sold-by-the-yard'],
	[94,62,127,9999,19.99,'https://bigzfabric.com/collections/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-4-pile-length/products/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-purple-sold-by-the-yard'],
	[8,7,5,9999,19.99,'https://bigzfabric.com/collections/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-4-pile-length/products/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-black-sold-by-the-yard'],
	[248,73,168,9999,19.99,'https://bigzfabric.com/collections/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-4-pile-length/products/faux-fake-fur-solid-gorilla-animal-long-pile-fabric-fuchsia-sold-by-the-yard'],
	[235,158,2,580,29.35,'https://www.fourrureshop.fr/produit/fausse-fourrure-jaune-or-poil-long-ac356/'], // €/m, g/ml
	[252,77,0,580,29.35,'https://www.fourrureshop.fr/produit/fausse-fourrure-orange-mandarine-poil-long-ac356/'], // €/m, g/ml
	[95,178,64,390,17.80,'https://www.fourrureshop.fr/produit/fausse-fourrure-pas-cher-vert-lime-poil-court-w160/'], // €/m, g/ml
	[0,0,0,390,17.80,'https://www.fourrureshop.fr/produit/fausse-fourrure-pas-cher-noire-poil-court-w160/'], // €/m, g/ml
	[29,19,17,1200,59.95,'https://www.fourrureshop.fr/produit/tissu-fausse-fourrure-facon-vison-brun-naturel-3125/'] // €/m, g/ml
]